name: PR handler

on:
  pull_request_target:

jobs:
  firmware_pipeline:
    name: Build Firmware
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build_firmware.yml
  comment:
    runs-on: ubuntu-latest
    name: Comment on PR
    needs:
      - firmware_pipeline
    permissions:
      pull-requests: write
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            **Built artifacts for commmit ${{ github.sha }}**:

            - [Ultra APP DFU Package](https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/ultra-dfu-app.zip)
            - [Ultra binaries](https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/ultra-firmware.zip)
            - [Lite APP DFU Package](https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/lite-dfu-app.zip)
            - [Ultra binaries](https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/lite-firmware.zip)
